"use strict";
/*
* This file has been generated by spacker.exe utility. Do not change this file manualy as your changes
* will get lost when the file is regenerated. Original content is located in *.c files.
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.Shaders = {
    vertex: require('./main.vertex.glsl'),
    fragment: require('./main.fragment.glsl'),
};
exports.ShadowMapShaders = {
    vertex: require('./shadowMap.vertex.glsl'),
    fragment: require('./shadowMap.fragment.glsl')
};
//# sourceMappingURL=shaders.js.map