/*
* This file has been generated by spacker.exe utility. Do not change this file manualy as your changes
* will get lost when the file is regenerated. Original content is located in *.c files.
*/

export var PulseShaders = {
    vertex: require('./pulse.vertex.glsl'),
    fragment: require('./pulse.fragment.glsl')
}
